* org-pivot-search for large Org files
This is a search command for org-mode.

It is somewhat a tweaked version of org-ql-find, which is shipped as part of
[[https://github.com/alphapapa/org-ql/][org-ql]]. It is created specifically for my use cases and supports advanced
customization and some extra features.

It is not for everyone​— It was originally planned to become part of [[https://github.com/akirak/org-dog][org-dog]],
which is based on a different model from Zettelkasten. However, this package
actually does not depend on org-dog, and I thought it could be useful even
independently, so I have decided to make it a separate package.
** Dependencies
- A fairly recent version of GNU Emacs
- [[https://github.com/alphapapa/org-ql][org-ql]] (required)
- [[https://github.com/akirak/org-dog][org-dog]] (optional for integration)
- [[https://github.com/akirak/org-nlink.el][org-nlink]] (optional for displaying link targets)
** Usage
=org-pivot-search-from-files= can be used both as an interactive function (i.e.
a command) and a function. As a function, it takes a set of Org files as
arguments and perform search on them. When used interactively, it is run on the
file of the current buffer.
